### ISSUE TITLE
Getting mlx.core.array getting text from a model manager

### ISSUE THREAD

**Issue by chimezie** [OoriData/Toolio#30]
Running this on an Apple M1 Max (using an arbitrary JSON schema file and mlx model)

```python
import asyncio
import click
import json
from toolio.llm_helper import model_manager
from toolio.common import response_text

CODING_PROMPT = """Give me some data in JSON, according to this schema: #!JSON_SCHEMA!#
"""

@click.command()
@click.option("--schema-file", type=str)
@click.argument('model')
def main(schema_file, model):
    with open(schema_file, "r") as f:
        schema = json.load(f)
    toolio_mm = model_manager(model)
    async def get_stuff(tmm):
        prompt = ("Give me some data in JSON, according to this schema: #!JSON_SCHEMA!#")
        print(await response_text(tmm.complete([{'role': 'user', 'content': prompt}], json_schema=schema)))
    asyncio.run(get_stuff(toolio_mm))
if __name__ == '__main__':
    main()
```

off a local installation of Toolio from git hash `aa32e7bc686cbca65abc4f32e98ff137de94e450` with mlx and mlx-lm git hashes:

```commandline
mlx % git rev-parse --verify HEAD
0308e9af712dafcc4414d329837778ddf4114c14
mlx-examples % git rev-parse --verify HEAD
d4ef909d4ab44d9f8cf89f5baa8a433d76d7d6b1
```

I get:

```commandline
Traceback (most recent call last):
  File "/tmp/toolio_test.py", line 22, in <module>
    main()
  File "/path/to/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/path/tosite-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/tosite-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/toolio_test.py", line 20, in main
    asyncio.run(get_stuff(toolio_mm))
  File "/path/to/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/path/to/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/tmp/toolio_test.py", line 19, in get_stuff
    print(await response_text(tmm.complete([{'role': 'user', 'content': prompt}], json_schema=schema)))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/site-packages/toolio/common.py", line 348, in response_text
    async for chunk in extract_content(resp_stream):
  File "/path/to/site-packages/toolio/common.py", line 334, in extract_content
    async for chunk in resp_stream:
  File "/path/to/site-packages/toolio/llm_helper.py", line 79, in complete
    async for resp in self._do_completion(messages, schema, responder, cache_prompt=cache_prompt,
  File "/path/to/site-packages/toolio/llm_helper.py", line 192, in _do_completion
    for result in self.model.completion(messages, schema, max_tokens=max_tokens, temp=temperature,
  File "/path/to/site-packages/toolio/schema_helper.py", line 297, in completion
    logits, cache = self._evaluate_prompt(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/site-packages/toolio/schema_helper.py", line 93, in _evaluate_prompt
    logits = self.model(mx.array(tokens)[None], cache)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[.. mlx bowels ..]
  File "/path/to/mlx-examples/llms/mlx_lm/models/base.py", line 119, in scaled_dot_product_attention
    return mx.fast.scaled_dot_product_attention(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: scaled_dot_product_attention(): incompatible function arguments. The following argument types are supported:
    1. scaled_dot_product_attention(q: array, k: array, v: array, *, scale: float,  mask: Optional[array] = None, stream: Union[None, Stream, Device] = None) -> array

Invoked with types: mlx.core.array, mlx.core.array, mlx.core.array, kwargs = { scale: float, mask: list }

```

This was the JSON schema file:

```json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://example.com/product.schema.json",
  "title": "Product",
  "description": "A product from Acme's catalog",
  "type": "object",
  "properties": {
    "productId": {
      "description": "The unique identifier for a product",
      "type": "integer"
    },
    "productName": {
      "description": "Name of the product",
      "type": "string"
    },
    "price": {
      "description": "The price of the product",
      "type": "number",
      "exclusiveMinimum": 0
    }
  },
  "required": [ "productId", "productName", "price" ]
}
```

**Comment by uogbuji** [comment]
Reproduced. Seems to be some change in`mlx_lm-0.20.5`. Things were working with the following:

```
pip show mlx mlx_lm
Name: mlx
Version: 0.21.1
Summary: A framework for machine learning on Apple silicon.
Home-page: https://github.com/ml-explore/mlx
Author: MLX Contributors
Author-email: mlx@group.apple.com
License: 
Location: /Users/uche/.local/venv/toolio/lib/python3.11/site-packages
Requires: 
Required-by: mlx-lm, Toolio
---
Name: mlx-lm
Version: 0.20.3
Summary: LLMs on Apple silicon with MLX and the Hugging Face Hub
Home-page: https://github.com/ml-explore/mlx-examples
Author: MLX Contributors
Author-email: mlx@group.apple.com
License: MITx
Location: /Users/uche/.local/venv/toolio/lib/python3.11/site-packages
Requires: jinja2, mlx, numpy, protobuf, pyyaml, transformers
Required-by: Toolio
```

After the update I get:

```
python demo/algebra_tutor.py
…
TypeError: scaled_dot_product_attention(): incompatible function arguments. The following argument types are supported:
    1. scaled_dot_product_attention(q: array, k: array, v: array, *, scale: float,  mask: Optional[array] = None, stream: Union[None, Stream, Device] = None) -> array

Invoked with types: mlx.core.array, mlx.core.array, mlx.core.array, kwargs = { scale: float, mask: list }
```

I'll try to dig in tomorrow.

**Comment by uogbuji** [comment]
OK I think I got this figured out. @chimezie try again with Toolio main branch update (see commit above) to confirm the fix. I've had changes accumulated for a 0.6.0 release, and I should be able to get that done tomorrow, if it looks good.

**Comment by chimezie** [comment]
It works beautifully now, thanks!

**Comment by uogbuji** [comment]
Note for posterity: we decided to go for a bigger set of fixes in 0.6.0.
